version: '3'

vars:
  BUNDLE_NAME: bear-notes-mcpb-{{now | date "20060102"}}.dxt
  
tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list
  
  inspector:
    desc: Run MCP inspector with Web UI
    cmds:
      - npx @modelcontextprotocol/inspector node --experimental-sqlite dist/main.js
      
  setup:
    desc: Project setup (install + build)
    cmds:
      - npm install
      - npm run build 

  style:
    desc: Runs linter and formatter with fixes
    cmds:
      - npm run lint
      - npm run format
  
  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf dist tmp *.dxt
      
  build:
    desc: Build with quality checks
    deps: [clean]
    cmds:
      - npm run check
      - npm run build
      
  # === Bundle Build ===

  pack:
    desc: Create production bundle
    deps: [build]
    cmds:
      - npx dxt validate manifest.json
      - rm -rf tmp/bundle && mkdir -p tmp/bundle
      - cp dist/*.js manifest.json package.json tmp/bundle/
      - cp assets/icon.png tmp/bundle/
      - cd tmp/bundle && npm install --omit=dev    
      - npx dxt pack tmp/bundle {{.BUNDLE_NAME}}
      - echo "Bundle created {{.BUNDLE_NAME}}"   
    
  info:
    desc: Show bundle info
    cmds:
      - npx dxt info {{.BUNDLE_NAME}}
      
  # === Version Management ===
  
  version:
    desc: Update version across all files
    prompt: "Confirm version update to {{.VERSION}}?"
    requires:
      vars: [VERSION]
    preconditions:
      - sh: echo "{{.VERSION}}" | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$'
        msg: "VERSION must follow semver format (x.y.z)"
    cmds:
      - |
        echo "Updating version to {{.VERSION}}"
        
        sed -i '' 's/"version": "[^"]*"/"version": "{{.VERSION}}"/' package.json
        
        sed -i '' 's/"version": "[^"]*"/"version": "{{.VERSION}}"/' manifest.json
        
        sed -i '' "s/export const APP_VERSION = '[^']*'/export const APP_VERSION = '{{.VERSION}}'/" src/config.ts
        
        echo "Version updated to {{.VERSION}} in package.json, manifest.json, and src/config.ts"

  # === Changelog ===
  
  changelog:
    silent: true
    desc: Extract changelog for specific version
    vars:
      VERSION: '{{.VERSION | default "1.0.0"}}'
    cmds:
      - |
        if [ ! -f CHANGELOG.md ]; then
          echo "CHANGELOG.md not found"
          exit 1
        fi
        
        # Extract content between ## [VERSION] and next ## section
        sed -n "/^## \[{{.VERSION}}\]/,/^## \[/p" CHANGELOG.md | \
        sed '$d' | \
        tail -n +3 | \
        sed '/^$/d'
