version: '3'

vars:
  BUNDLE_NAME: bear-notes-mcp.dxt
  
tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list
      
  # === Development ===
  
  setup:
    desc: Project setup (install + build)
    cmds:
      - npm install
      - npm run build
      
  dev:
    desc: Run development server
    cmds:
      - npm run dev
  
  style:
    desc: Runs linter and formatter with fixes
    cmds:
      - npm run lint
      - npm run format
      
  # === Build ===
  
  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf dist tmp *.dxt
      
  build:
    desc: Build with quality checks
    deps: [clean]
    cmds:
      - npm run check
      - npm run build
      
  # === Bundle ===
  
  pack:
    desc: Create production bundle
    deps: [build]
    cmds:
      - npx dxt validate manifest.json
      - rm -rf tmp/bundle && mkdir -p tmp/bundle
      - cp dist/*.js manifest.json package.json README.md tmp/bundle/
      - cp assets/icon.png tmp/bundle/
      - cd tmp/bundle && npm install --omit=dev
      - npx dxt pack tmp/bundle {{.BUNDLE_NAME}}
      - echo "✅ Bundle created {{.BUNDLE_NAME}}"
      
  info:
    desc: Show bundle info
    cmds:
      - npx dxt info {{.BUNDLE_NAME}}
      
  # === CI ===
  
  ci:
    desc: Full CI pipeline
    cmds:
      - npm install
      - task pack
      - echo "✅ CI completed"